THIS_MK_DIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
COMMON_DIR := $(THIS_MK_DIR)

OPT_DEFS += -DMULTIMODE_ENABLE
OPT_DEFS += -DENTRY_STOP_MODE
OPT_DEFS += -DNO_USB_STARTUP_CHECK
OPT_DEFS += -DWWDG_ENABLE

UART_DRIVER_REQUIRED = yes

COMMON_VPATH += $(COMMON_DIR)

SRC += $(COMMON_DIR)/bt_task.c
SRC += $(COMMON_DIR)/retarget_suspend.c
SRC += $(COMMON_DIR)/lp_sleep.c
SRC += $(COMMON_DIR)/wb32_wwdg.c
SRC += $(COMMON_DIR)/wwdg.c

LDFLAGS += -L $(COMMON_DIR)/ -l_bts
